<h1 style="text-align:center">   
      <font color = White >
            <span style='font-family:Georgia'>
                Credit Card Fraud Detection: Project 4
            </span>   
        </font>    
</h1>
<h3 style="text-align:CENTER">   
      <font color = white >
            <span style='font-family:Georgia'>
                By : Team 9
            </span>   
        </font>    
</h3>
<hr style="width:100%;height:5px;border-width:0;color:gray;background-color:gray">
<center>

## Import Python Libraries:

In [1]:
# Lets import the required libraries and packages
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn import metrics
from sklearn.metrics import precision_recall_curve, roc_auc_score
from sklearn.metrics import precision_score, recall_score, confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, f1_score

import warnings
warnings.filterwarnings("ignore")

### Reading the train dataset

In [2]:
# load data
fraud_train = pd.read_csv("fraudTrain.csv")
fraud_train

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,37.7175,-112.4777,258,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0
1296671,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,39.2667,-77.5101,100,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0
1296672,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,32.9396,-105.8189,899,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0
1296673,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,43.3526,-102.5411,1126,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0
1296674,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0

### Inspect train dataset

In [3]:
# Lets check the info to see the types of the feature variables and the null values present
fraud_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [4]:
# Summary of the dataset
fraud_train.describe(include='all')

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
count,1.296675e+06,1296675,1.296675e+06,1296675,1296675,1.296675e+06,1296675,1296675,1296675,1296675,...,1.296675e+06,1.296675e+06,1.296675e+06,1296675,1296675,1296675,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06
unique,NaN,1274791,NaN,693,14,NaN,352,481,2,983,...,NaN,NaN,NaN,494,968,1296675,NaN,NaN,NaN,NaN
top,NaN,2019-04-22 16:02:01,NaN,fraud_Kilback LLC,gas_transport,NaN,Christopher,Smith,F,0069 Robin Brooks Apt. 695,...,NaN,NaN,NaN,Film/video editor,1977-03-23,0b242abb623afc578575680df30655b9,NaN,NaN,NaN,NaN
freq,NaN,4,NaN,4403,131659,NaN,26669,28794,709863,3123,...,NaN,NaN,NaN,9779,5636,1,NaN,NaN,NaN,NaN
mean,6.483370e+05,NaN,4.171920e+17,NaN,NaN,7.035104e+01,NaN,NaN,NaN,NaN,...,3.853762e+01,-9.022634e+01,8.882444e+04,NaN,NaN,NaN,1.349244e+09,3.853734e+01,-9.022646e+01,5.788652e-03
std,3.743180e+05,NaN,1.308806e+18,NaN,NaN,1.603160e+02,NaN,NaN,NaN,NaN,...,5.075808e+00,1.375908e+01,3.019564e+05,NaN,NaN,NaN,1.284128e+07,5.109788e+00,1.377109e+01,7.586269e-02
min,0.000000e+00,NaN,6.041621e+10,NaN,NaN,1.000000e+00,NaN,NaN,NaN,NaN,...,2.002710e+01,-1.656723e+02,2.300000e+01,NaN,NaN,NaN,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00
25%,3.241685e+05,NaN,1.800429e+14,NaN,NaN,9.650000e+00,NaN,NaN,NaN,NaN,...,3.462050e+01,-9.679800e+01,7.430000e+02,NaN,NaN,NaN,1.338751e+09,3.473357e+01,-9.689728e+01,0.000000e+00
50%,6.483370e+05,NaN,3.521417e+15,NaN,NaN,4.752000e+01,NaN,NaN,NaN,NaN,...,3.935430e+01,-8.747690e+01,2.456000e+03,NaN,NaN,NaN,1.349250e+09,3.936568e+01,-8.743839e+01,0.000000e+00
75%,9.725055e+05,NaN,4.642255e+15,NaN,NaN,8.314000e+01,NaN,NaN,NaN,NaN,...,4.194040e+01,-8.015800e+01,2.032800e+04,NaN,NaN,NaN,1.359385e+09,4.195716e+01,-8.023680e+01,0.000000e+00
max,1.296674e+06,NaN,4.992346e+18,NaN,NaN,2.894890e+04,NaN,NaN,NaN,NaN,...,6.669330e+01,-6.795030e+01,2.906700e+06,NaN,NaN,NaN,1.371817e+09,6.751027e+01,-6.695090e+01,1.000000e+00

### Duplicate value analysis

In [5]:
# Dimension of data set
print(fraud_train.shape)
fraud_train.drop_duplicates()
print(fraud_train.shape)

(1296675, 23)
(1296675, 23)

No duplicate found in data set

## Data Cleaning Proceess

In [6]:
# Lets check the null values present in the dataset in each column
print(fraud_train.isnull().sum())

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

No null values found

### Dropping Columns

In [7]:
# Lets delete unwanted column
fraud_train= fraud_train.drop(['Unnamed: 0'],axis=1)
fraud_train= fraud_train.drop(['first'],axis=1)
fraud_train= fraud_train.drop(['last'],axis=1)

fraud_train.shape

(1296675, 20)

In [8]:
# Identifying columns which has only one unique value
print(fraud_train.nunique(dropna=False).sort_values())

is_fraud                       2
gender                         2
category                      14
state                         51
job                          494
merchant                     693
city_pop                     879
city                         894
dob                          968
lat                          968
long                         969
zip                          970
street                       983
cc_num                       983
amt                        52928
merch_lat                1247805
trans_date_trans_time    1274791
unix_time                1274823
merch_long               1275745
trans_num                1296675
dtype: int64

### Data Transformation

In [9]:
# Lets convert the columns to appropriate formats
fraud_train['trans_date_trans_time']= pd.to_datetime(fraud_train['trans_date_trans_time'])

In [10]:
fraud_train['dob'] = pd.to_datetime(fraud_train['dob'], errors='coerce')

In [11]:
fraud_train['trans_Date']=fraud_train.trans_date_trans_time.dt.date
fraud_train['trans_Time']=fraud_train.trans_date_trans_time.dt.time
fraud_train.trans_Date = pd.to_datetime(fraud_train['trans_Date'],format='%Y-%m-%d')

In [12]:
fraud_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 22 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trans_date_trans_time  1296675 non-null  datetime64[ns]
 1   cc_num                 1296675 non-null  int64
 2   merchant               1296675 non-null  object
 3   category               1296675 non-null  object
 4   amt                    1296675 non-null  float64
 5   gender                 1296675 non-null  object
 6   street                 1296675 non-null  object
 7   city                   1296675 non-null  object
 8   state                  1296675 non-null  object
 9   zip                    1296675 non-null  int64
 10  lat                    1296675 non-null  float64
 11  long                   1296675 non-null  float64
 12  city_pop               1296675 non-null  int64
 13  job                    1296675 non-null  object
 14  dob                    1296675 non-null  datetime64[ns]
 15  trans_num              1296675 non-null  object
 16  unix_time              1296675 non-null  int64
 17  merch_lat              1296675 non-null  float64
 18  merch_long             1296675 non-null  float64
 19  is_fraud               1296675 non-null  int64
 20  trans_Date             1296675 non-null  datetime64[ns]
 21  trans_Time             1296675 non-null  object
dtypes: datetime64[ns](3), float64(5), int64(5), object(9)
memory usage: 217.6+ MB

### Binning of `state` column as it is having 51 unique values

In [13]:
def label_states (row):
    if row['state'] in ['CT','ME','MA','NH','NJ','NY','PA','RI','VT']:
        return 'Northeast'
    if row['state'] in ['IL','IN','IA','KS','MI','MN','MO','NE','ND','OH','SD','WI']:
        return 'Midwest'
    if row['state'] in ['AL','AR','DE','DC','FL','GA','KY','LA','MD','MS','NC','OK','SC','TN','Tx','VA','WV']:
        return 'South'
    else:
        return 'West'

In [14]:
fraud_train['state_bin'] = fraud_train.apply(lambda row: label_states(row), axis=1)
fraud_train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,city,state,zip,...,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,trans_Date,trans_Time,state_bin
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,561 Perry Cove,Moravian Falls,NC,28654,...,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,2019-01-01,00:00:18,South
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,43039 Riley Greens Suite 393,Orient,WA,99160,...,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,2019-01-01,00:00:44,West
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,M,594 White Dale Suite 530,Malad City,ID,83252,...,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,2019-01-01,00:00:51,West
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,...,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,2019-01-01,00:01:16,West
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,M,408 Bradley Rest,Doe Hill,VA,24433,...,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,2019-01-01,00:03:06,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,M,162 Jessica Row Apt. 072,Hatch,UT,84735,...,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0,2020-06-21,12:12:08,West
1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,M,8617 Holmes Terrace Suite 651,Tuscarora,MD,21790,...,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0,2020-06-21,12:12:19,South
1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,M,1632 Cohen Drive Suite 639,High Rolls Mountain Park,NM,88325,...,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0,2020-06-21,12:12:32,West
1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,M,42933 Ryan Underpass,Manderson,SD,57756,...,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0,2020-06-21,12:13:36,Midwest
1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,M,135 Joseph Mountains,Sula,MT,59871,...,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0,2020-06-21,12:13:37,West

In [15]:
fraud_train["state_bin"].describe()

count     1296675
unique          4
top         South
freq       399915
Name: state_bin, dtype: object

### Deriving `age` on transaction day from "dob" variable and binning of age variable

In [16]:

fraud_train["age"] = fraud_train["dob"].apply(lambda x: (pd.to_datetime('now').year - x.year))

### Binning of age

In [17]:
bin_manual = [0, 20, 30, 40, 50, 60, 70, 80, 90, 100]
labs = ['0-20', '20-30', '30-40', '40-50','50-60','60-70','70-80', '80-90','90-100']
fraud_train['age_bin'] = pd.cut(fraud_train.age, bins=bin_manual, labels=labs)

In [18]:
fraud_train[['age_bin','age']].head()

  age_bin  age
0   30-40   36
1   40-50   46
2   60-70   62
3   50-60   57
4   30-40   38

###  Deriving `trans_Year`, `trans_year_month`, `trans_Month`, `trans_Hour`, `trans_Day`, `trans_weekday` of transaction from trans_date_trans_time variable

In [19]:
fraud_train['trans_Year']=fraud_train.trans_Date.dt.year
fraud_train['trans_year_month'] = fraud_train.trans_Date.dt.to_period('M')
fraud_train['trans_Month']=fraud_train.trans_Date.dt.month
fraud_train['trans_Hour']=fraud_train.trans_date_trans_time.dt.hour
fraud_train['trans_Day']=fraud_train.trans_Date.dt.day
fraud_train['trans_weekday'] = fraud_train.trans_Date.dt.day_name()

fraud_train.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,city,state,zip,...,trans_Time,state_bin,age,age_bin,trans_Year,trans_year_month,trans_Month,trans_Hour,trans_Day,trans_weekday
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,561 Perry Cove,Moravian Falls,NC,28654,...,00:00:18,South,36,30-40,2019,2019-01,1,0,1,Tuesday
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,43039 Riley Greens Suite 393,Orient,WA,99160,...,00:00:44,West,46,40-50,2019,2019-01,1,0,1,Tuesday
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,M,594 White Dale Suite 530,Malad City,ID,83252,...,00:00:51,West,62,60-70,2019,2019-01,1,0,1,Tuesday
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,...,00:01:16,West,57,50-60,2019,2019-01,1,0,1,Tuesday
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,M,408 Bradley Rest,Doe Hill,VA,24433,...,00:03:06,South,38,30-40,2019,2019-01,1,0,1,Tuesday

### Checking the correlations between the variables

In [20]:
# lets check the correlation amongst the features
# Select only the numeric columns
numeric_cols = fraud_train.select_dtypes(include=[np.number])

# Compute the correlation matrix
cor = numeric_cols.corr()


# Define a threshold for high correlation
threshold = 0.8

# Find pairs of features with high correlation
high_corr_pairs = []
for i in range(len(cor.columns)):
    for j in range(i):
        if abs(cor.iloc[i, j]) > threshold:
            high_corr_pairs.append((cor.columns[i], cor.columns[j], cor.iloc[i, j]))

# Display the high correlation pairs
for pair in high_corr_pairs:
    print(f"Columns '{pair[0]}' and '{pair[1]}' have a correlation of {pair[2]:.2f}")

Columns 'long' and 'zip' have a correlation of -0.91
Columns 'merch_lat' and 'lat' have a correlation of 0.99
Columns 'merch_long' and 'zip' have a correlation of -0.91
Columns 'merch_long' and 'long' have a correlation of 1.00

### Dropping the variables who have high correlation values

In [21]:
# Columns to drop based on the correlation analysis
columns_to_drop = ['merch_lat', 'merch_long']  # Choose to keep 'lat' and 'zip' or based on other criteria

# Drop the columns
fraud_train = fraud_train.drop(columns=columns_to_drop)

# Display the shape of the new DataFrame to verify columns have been dropped
print(fraud_train.shape)

(1296675, 29)

In [22]:
df=fraud_train.copy()

In [23]:
# Drop the 'trans_date_time' column from the DataFrame in place
fraud_train.drop(columns=['trans_date_trans_time','state'], axis=1, inplace=True)

# Display the first few rows of the modified DataFrame to verify the column has been removed
print(fraud_train.head())

             cc_num                            merchant       category  \
0  2703186189652095          fraud_Rippin, Kub and Mann       misc_net
1      630423337322     fraud_Heller, Gutmann and Zieme    grocery_pos
2    38859492057661                fraud_Lind-Buckridge  entertainment
3  3534093764340240  fraud_Kutch, Hermiston and Farrell  gas_transport
4   375534208663984                 fraud_Keeling-Crist       misc_pos

      amt gender                        street            city    zip  \
0    4.97      F                561 Perry Cove  Moravian Falls  28654
1  107.23      F  43039 Riley Greens Suite 393          Orient  99160
2  220.11      M      594 White Dale Suite 530      Malad City  83252
3   45.00      M   9443 Cynthia Court Apt. 038         Boulder  59632
4   41.96      M              408 Bradley Rest        Doe Hill  24433

       lat      long  ...  trans_Time state_bin age age_bin  trans_Year  \
0  36.0788  -81.1781  ...    00:00:18     South  36   30-40        2019
1  48.8878 -118.2105  ...    00:00:44      West  46   40-50        2019
2  42.1808 -112.2620  ...    00:00:51      West  62   60-70        2019
3  46.2306 -112.1138  ...    00:01:16      West  57   50-60        2019
4  38.4207  -79.4629  ...    00:03:06     South  38   30-40        2019

   trans_year_month trans_Month trans_Hour trans_Day  trans_weekday
0           2019-01           1          0         1        Tuesday
1           2019-01           1          0         1        Tuesday
2           2019-01           1          0         1        Tuesday
3           2019-01           1          0         1        Tuesday
4           2019-01           1          0         1        Tuesday

[5 rows x 27 columns]

In [24]:

# `` Binning 'trans_Hour' into categories
def categorize_hour(hour):
    if 0 <= hour < 6:
        return 'Night'
    elif 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 18:
        return 'Afternoon'
    else:
        return 'Evening'

fraud_train['hour_bin'] = fraud_train['trans_Hour'].apply(categorize_hour)

# One-Hot Encoding 'hour_bin'
fraud_train = pd.get_dummies(fraud_train, columns=['hour_bin'], prefix='hour_bin')

# Label Encoding (if needed) for ordinal features 

label_encoder = LabelEncoder()
fraud_train['age_bin_encoded'] = label_encoder.fit_transform(fraud_train['age_bin'])

# One-Hot Encoding for nominal features like 'category' or 'state'
fraud_train = pd.get_dummies(fraud_train, columns=['category', 'state_bin'], prefix=['category', 'state'])

In [25]:
# One-Hot Encoding the 'gender' column
fraud_train = pd.get_dummies(fraud_train, columns=['gender'], prefix='gender')

# Display the first few rows to verify the encoding
fraud_train.head()

,cc_num,merchant,amt,street,city,zip,lat,long,city_pop,job,...,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,state_Midwest,state_Northeast,state_South,state_West,gender_F,gender_M
0,2703186189652095,"fraud_Rippin, Kub and Mann",4.97,561 Perry Cove,Moravian Falls,28654,36.0788,-81.1781,3495,"Psychologist, counselling",...,False,False,False,False,False,False,True,False,True,False
1,630423337322,"fraud_Heller, Gutmann and Zieme",107.23,43039 Riley Greens Suite 393,Orient,99160,48.8878,-118.2105,149,Special educational needs teacher,...,False,False,False,False,False,False,False,True,True,False
2,38859492057661,fraud_Lind-Buckridge,220.11,594 White Dale Suite 530,Malad City,83252,42.1808,-112.2620,4154,Nature conservation officer,...,False,False,False,False,False,False,False,True,False,True
3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",45.00,9443 Cynthia Court Apt. 038,Boulder,59632,46.2306,-112.1138,1939,Patent attorney,...,False,False,False,False,False,False,False,True,False,True
4,375534208663984,fraud_Keeling-Crist,41.96,408 Bradley Rest,Doe Hill,24433,38.4207,-79.4629,99,Dance movement psychotherapist,...,False,False,False,False,False,False,True,False,False,True

In [26]:
fraud_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 49 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   cc_num                   1296675 non-null  int64
 1   merchant                 1296675 non-null  object
 2   amt                      1296675 non-null  float64
 3   street                   1296675 non-null  object
 4   city                     1296675 non-null  object
 5   zip                      1296675 non-null  int64
 6   lat                      1296675 non-null  float64
 7   long                     1296675 non-null  float64
 8   city_pop                 1296675 non-null  int64
 9   job                      1296675 non-null  object
 10  dob                      1296675 non-null  datetime64[ns]
 11  trans_num                1296675 non-null  object
 12  unix_time                1296675 non-null  int64
 13  is_fraud                 1296675 non-null  int64
 14  trans_Date               1296675 non-null  datetime64[ns]
 15  trans_Time               1296675 non-null  object
 16  age                      1296675 non-null  int64
 17  age_bin                  1296675 non-null  category
 18  trans_Year               1296675 non-null  int32
 19  trans_year_month         1296675 non-null  period[M]
 20  trans_Month              1296675 non-null  int32
 21  trans_Hour               1296675 non-null  int32
 22  trans_Day                1296675 non-null  int32
 23  trans_weekday            1296675 non-null  object
 24  hour_bin_Afternoon       1296675 non-null  bool
 25  hour_bin_Evening         1296675 non-null  bool
 26  hour_bin_Morning         1296675 non-null  bool
 27  hour_bin_Night           1296675 non-null  bool
 28  age_bin_encoded          1296675 non-null  int64
 29  category_entertainment   1296675 non-null  bool
 30  category_food_dining     1296675 non-null  bool
 31  category_gas_transport   1296675 non-null  bool
 32  category_grocery_net     1296675 non-null  bool
 33  category_grocery_pos     1296675 non-null  bool
 34  category_health_fitness  1296675 non-null  bool
 35  category_home            1296675 non-null  bool
 36  category_kids_pets       1296675 non-null  bool
 37  category_misc_net        1296675 non-null  bool
 38  category_misc_pos        1296675 non-null  bool
 39  category_personal_care   1296675 non-null  bool
 40  category_shopping_net    1296675 non-null  bool
 41  category_shopping_pos    1296675 non-null  bool
 42  category_travel          1296675 non-null  bool
 43  state_Midwest            1296675 non-null  bool
 44  state_Northeast          1296675 non-null  bool
 45  state_South              1296675 non-null  bool
 46  state_West               1296675 non-null  bool
 47  gender_F                 1296675 non-null  bool
 48  gender_M                 1296675 non-null  bool
dtypes: bool(24), category(1), datetime64[ns](2), float64(3), int32(4), int64(7), object(7), period[M](1)
memory usage: 248.6+ MB

In [27]:
# One-hot encode categorical columns
categorical_cols = ['trans_weekday']  # Add other categorical columns as needed
fraud_train = pd.get_dummies(fraud_train, columns=categorical_cols)

In [28]:
fraud_train.drop(columns=['gender_F'],axis=1, inplace=True) 
fraud_train.drop(columns=['trans_num'],axis=1, inplace=True)

In [29]:
fraud_train

,cc_num,merchant,amt,street,city,zip,lat,long,city_pop,job,...,state_South,state_West,gender_M,trans_weekday_Friday,trans_weekday_Monday,trans_weekday_Saturday,trans_weekday_Sunday,trans_weekday_Thursday,trans_weekday_Tuesday,trans_weekday_Wednesday
0,2703186189652095,"fraud_Rippin, Kub and Mann",4.97,561 Perry Cove,Moravian Falls,28654,36.0788,-81.1781,3495,"Psychologist, counselling",...,True,False,False,False,False,False,False,False,True,False
1,630423337322,"fraud_Heller, Gutmann and Zieme",107.23,43039 Riley Greens Suite 393,Orient,99160,48.8878,-118.2105,149,Special educational needs teacher,...,False,True,False,False,False,False,False,False,True,False
2,38859492057661,fraud_Lind-Buckridge,220.11,594 White Dale Suite 530,Malad City,83252,42.1808,-112.2620,4154,Nature conservation officer,...,False,True,True,False,False,False,False,False,True,False
3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",45.00,9443 Cynthia Court Apt. 038,Boulder,59632,46.2306,-112.1138,1939,Patent attorney,...,False,True,True,False,False,False,False,False,True,False
4,375534208663984,fraud_Keeling-Crist,41.96,408 Bradley Rest,Doe Hill,24433,38.4207,-79.4629,99,Dance movement psychotherapist,...,True,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,30263540414123,fraud_Reichel Inc,15.56,162 Jessica Row Apt. 072,Hatch,84735,37.7175,-112.4777,258,Geoscientist,...,False,True,True,False,False,False,True,False,False,False
1296671,6011149206456997,fraud_Abernathy and Sons,51.70,8617 Holmes Terrace Suite 651,Tuscarora,21790,39.2667,-77.5101,100,"Production assistant, television",...,True,False,True,False,False,False,True,False,False,False
1296672,3514865930894695,fraud_Stiedemann Ltd,105.93,1632 Cohen Drive Suite 639,High Rolls Mountain Park,88325,32.9396,-105.8189,899,Naval architect,...,False,True,True,False,False,False,True,False,False,False
1296673,2720012583106919,"fraud_Reinger, Weissnat and Strosin",74.90,42933 Ryan Underpass,Manderson,57756,43.3526,-102.5411,1126,Volunteer coordinator,...,False,False,True,False,False,False,True,False,False,False
1296674,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",4.30,135 Joseph Mountains,Sula,59871,45.8433,-113.8748,218,"Therapist, horticultural",...,False,True,True,False,False,False,True,False,False,False

In [30]:
# Frequency Encoding for high-cardinality categorical columns
def frequency_encoding(df, column):
    freq_encoding = df[column].value_counts()
    df[column + '_freq'] = df[column].map(freq_encoding)
    return df

# Apply frequency encoding to 'merchant', 'street', 'city', 'job'
columns_to_encode = ['merchant', 'street', 'city', 'job']
for col in columns_to_encode:
    fraud_train = frequency_encoding(fraud_train, col)
    fraud_train.drop(columns=[col], inplace=True)  # Drop original column if no longer needed

fraud_train.head()

,cc_num,amt,zip,lat,long,city_pop,dob,unix_time,is_fraud,trans_Date,...,trans_weekday_Monday,trans_weekday_Saturday,trans_weekday_Sunday,trans_weekday_Thursday,trans_weekday_Tuesday,trans_weekday_Wednesday,merchant_freq,street_freq,city_freq,job_freq
0,2703186189652095,4.97,28654,36.0788,-81.1781,3495,1988-03-09,1325376018,0,2019-01-01,...,False,False,False,False,True,False,1267,2028,2028,3545
1,630423337322,107.23,99160,48.8878,-118.2105,149,1978-06-21,1325376044,0,2019-01-01,...,False,False,False,False,True,False,2503,3030,3545,5099
2,38859492057661,220.11,83252,42.1808,-112.2620,4154,1962-01-19,1325376051,0,2019-01-01,...,False,False,False,False,True,False,1895,503,503,511
3,3534093764340240,45.00,59632,46.2306,-112.1138,1939,1967-01-12,1325376076,0,2019-01-01,...,False,False,False,False,True,False,2613,493,493,2530
4,375534208663984,41.96,24433,38.4207,-79.4629,99,1986-03-28,1325376186,0,2019-01-01,...,False,False,False,False,True,False,1592,2017,2017,2017

In [31]:
fraud_train.drop(columns=['dob'], inplace=True)

In [32]:
# Drop the original 'trans_Date' column
fraud_train.drop(columns=['trans_Date'], inplace=True)

In [33]:
# Convert 'trans_year_month' (which is a Period) to a numeric format (e.g., YYYYMM)
fraud_train['trans_year_month'] = fraud_train['trans_year_month'].astype(str).str.replace('-', '').astype(int)

In [34]:
# Convert 'trans_Time' to seconds since midnight
fraud_train['trans_Time'] = pd.to_datetime(fraud_train['trans_Time'], format='%H:%M:%S').dt.hour * 3600 + \
                            pd.to_datetime(fraud_train['trans_Time'], format='%H:%M:%S').dt.minute * 60 + \
                            pd.to_datetime(fraud_train['trans_Time'], format='%H:%M:%S').dt.second

### Splitting Data for Training and Testing

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE

In [36]:
# Define features and target variable
X = fraud_train.drop(columns=['is_fraud', 'cc_num','unix_time','age_bin'])  # Drop irrelevant columns if necessary
y = fraud_train['is_fraud']

In [37]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [38]:
# Standardize the data (important before applying PCA)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Apply SMOTE to the scaled training data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

# Initialize PCA and fit it to the SMOTE-transformed training data
pca = PCA(n_components=20)  # Adjust n_components as needed
X_train_pca = pca.fit_transform(X_train_smote)

# Transform the test data using the fitted PCA
X_test_pca = pca.transform(X_test_scaled)

# Initialize and train the Logistic Regression model
log_reg = LogisticRegression(max_iter=1000, solver='liblinear')
log_reg.fit(X_train_pca, y_train_smote)

# Predict on the test data
y_pred = log_reg.predict(X_test_pca)

# Generate the classification report
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.89      0.94    386718
           1       0.04      0.82      0.08      2285

    accuracy                           0.89    389003
   macro avg       0.52      0.85      0.51    389003
weighted avg       0.99      0.89      0.94    389003

In [40]:
from sklearn.model_selection import RandomizedSearchCV


# Define the parameter grid for RandomizedSearchCV
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],  # Regularization strength
    'solver': ['liblinear', 'lbfgs'],     # Optimization algorithms
    'penalty': ['l1', 'l2'],               # Regularization types
}

# Initialize Logistic Regression model
log_reg = LogisticRegression(max_iter=1000)

# Initialize RandomizedSearchCV
random_search = RandomizedSearchCV(
    estimator=log_reg,
    param_distributions=param_grid,
    n_iter=10,  # Number of parameter settings to sample
    cv=5,       # Number of folds in cross-validation
    verbose=2,
    random_state=42,
    n_jobs=-1   # Use all available cores
)

# Fit RandomizedSearchCV
random_search.fit(X_train_pca, y_train_smote)

# Get the best parameters and best model
best_params = random_search.best_params_
best_model = random_search.best_estimator_

print(f"Best Parameters: {best_params}")

# Make predictions on the test set with the best model
y_pred_best = best_model.predict(X_test_pca)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END ..............C=0.001, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END .................C=10, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END ................C=0.1, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END ................C=0.1, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END .................C=10, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END .................C=10, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END .................C=10, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END ................C=0.1, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END ................C=0.1, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END .................C=10, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END ................C=0.1, penalty=l1, solver=liblinear; total time= 1.0min
[CV] END ....................C=0.1, penalty=l2, solver=lbfgs; total time=   3.3s
[CV] END ....................C=0.1, penalty=l2, solver=lbfgs; total time=   4.4s
[CV] END ....................C=0.1, penalty=l2, solver=lbfgs; total time=   2.9s
[CV] END ....................C=0.1, penalty=l2, solver=lbfgs; total time=   5.8s
[CV] END ....................C=0.1, penalty=l2, solver=lbfgs; total time=   4.7s
[CV] END ....................C=0.1, penalty=l1, solver=lbfgs; total time=   0.7s
[CV] END ....................C=0.1, penalty=l1, solver=lbfgs; total time=   0.6s
[CV] END ....................C=0.1, penalty=l1, solver=lbfgs; total time=   0.8s
[CV] END ....................C=0.1, penalty=l1, solver=lbfgs; total time=   0.8s
[CV] END ....................C=0.1, penalty=l1, solver=lbfgs; total time=   0.8s
[CV] END ......................C=1, penalty=l1, solver=lbfgs; total time=   0.8s
[CV] END ......................C=1, penalty=l1, solver=lbfgs; total time=   0.6s
[CV] END ......................C=1, penalty=l1, solver=lbfgs; total time=   0.7s
[CV] END ......................C=1, penalty=l1, solver=lbfgs; total time=   0.9s
[CV] END ......................C=1, penalty=l1, solver=lbfgs; total time=   1.1s
[CV] END ..................C=0.001, penalty=l1, solver=lbfgs; total time=   0.8s
[CV] END ..................C=0.001, penalty=l1, solver=lbfgs; total time=   1.0s
[CV] END ..................C=0.001, penalty=l1, solver=lbfgs; total time=   0.9s
[CV] END ..................C=0.001, penalty=l1, solver=lbfgs; total time=   0.5s
[CV] END ..................C=0.001, penalty=l1, solver=lbfgs; total time=   0.6s
[CV] END ....................C=100, penalty=l1, solver=lbfgs; total time=   0.6s
[CV] END ....................C=100, penalty=l1, solver=lbfgs; total time=   0.4s
[CV] END ....................C=100, penalty=l1, solver=lbfgs; total time=   0.8s
[CV] END ....................C=100, penalty=l1, solver=lbfgs; total time=   0.6s
[CV] END ...................C=0.01, penalty=l1, solver=lbfgs; total time=   0.5s
[CV] END ....................C=100, penalty=l1, solver=lbfgs; total time=   1.1s
[CV] END ...................C=0.01, penalty=l1, solver=lbfgs; total time=   0.5s
[CV] END ...................C=0.01, penalty=l1, solver=lbfgs; total time=   0.7s
[CV] END ...................C=0.01, penalty=l1, solver=lbfgs; total time=   0.9s
[CV] END ...................C=0.01, penalty=l1, solver=lbfgs; total time=   0.4s
[CV] END .................C=10, penalty=l2, solver=liblinear; total time=  21.9s
[CV] END ..............C=0.001, penalty=l1, solver=liblinear; total time=  23.0s
[CV] END .................C=10, penalty=l2, solver=liblinear; total time=  22.4s
[CV] END .................C=10, penalty=l2, solver=liblinear; total time=  22.5s
[CV] END .................C=10, penalty=l2, solver=liblinear; total time=  22.8s
[CV] END .................C=10, penalty=l2, solver=liblinear; total time=  22.8s
[CV] END ..............C=0.001, penalty=l1, solver=liblinear; total time=  23.2s
[CV] END ..............C=0.001, penalty=l1, solver=liblinear; total time=  23.4s
[CV] END ..............C=0.001, penalty=l1, solver=liblinear; total time=  23.5s
Best Parameters: {'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}

In [41]:

# Print the classification report for the best model
print("Classification Report for the Best Model:")
print(classification_report(y_test, y_pred_best))

Classification Report for the Best Model:
              precision    recall  f1-score   support

           0       1.00      0.89      0.94    386718
           1       0.04      0.82      0.08      2285

    accuracy                           0.89    389003
   macro avg       0.52      0.85      0.51    389003
weighted avg       0.99      0.89      0.94    389003

In [42]:
import joblib

# Assuming you have already fitted the encoders and scaler
# Save the LabelEncoder
joblib.dump(label_encoder, 'label_encoder.joblib')


# Save the Standard Scaler
joblib.dump(scaler, 'scaler.joblib')


# Save RFE 
joblib.dump(pca, 'PCA.joblib')


# Save the model itself
joblib.dump(best_model, 'logisticModelPCA.joblib')

['logisticModelPCA.joblib']

In [ ]:
X_train

,amt,zip,lat,long,city_pop,trans_Time,age,trans_Year,trans_year_month,trans_Month,...,trans_weekday_Monday,trans_weekday_Saturday,trans_weekday_Sunday,trans_weekday_Thursday,trans_weekday_Tuesday,trans_weekday_Wednesday,merchant_freq,street_freq,city_freq,job_freq
992821,2.38,40077,38.4921,-85.4524,564,71763,28,2020,202002,2,...,False,False,True,False,False,False,3634,2949,2949,5504
833489,6.53,82901,41.6060,-109.2300,27971,72609,40,2019,201912,12,...,False,False,False,False,False,True,2306,2562,2562,2562
517107,6.62,46322,41.5500,-87.4569,23727,61188,42,2019,201908,8,...,False,False,True,False,False,False,2017,1526,1526,2567
166051,24.86,22046,38.8856,-77.1802,116155,30073,41,2019,201903,3,...,False,False,False,False,False,False,1228,1021,1021,1502
473161,25.65,39073,32.1530,-90.1217,19685,53225,40,2019,201907,7,...,False,True,False,False,False,False,2440,3046,3046,4595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110268,72.38,54896,45.8327,-91.0144,1478,10168,59,2019,201903,3,...,True,False,False,False,False,False,2593,1055,1055,2101
259178,2.33,6441,41.4682,-72.5751,5438,24844,60,2019,201905,5,...,False,False,False,True,False,False,2503,1033,1033,5203
131932,118.27,87117,35.0203,-106.5503,310,78387,46,2019,201903,3,...,False,False,False,False,False,True,2338,1011,1011,8680
671155,5.60,56729,48.6669,-96.5969,140,34106,82,2019,201910,10,...,False,False,True,False,False,False,2351,1047,1047,1571
121958,140.73,29320,34.9572,-81.9916,530,65595,35,2019,201903,3,...,False,True,False,False,False,False,1836,2044,4096,2044

In [ ]:
selected_features

Index(['amt', 'trans_Time', 'age', 'trans_year_month', 'trans_Month',
       'trans_Day', 'hour_bin_Afternoon', 'hour_bin_Evening',
       'hour_bin_Morning', 'hour_bin_Night', 'category_grocery_pos',
       'category_health_fitness', 'category_home', 'category_kids_pets',
       'category_misc_net', 'category_shopping_net', 'merchant_freq',
       'street_freq', 'city_freq', 'job_freq'],
      dtype='object')