<h1 style="text-align:center">   
      <font color = White >
            <span style='font-family:Georgia'>
                Credit Card Fraud Detection: Project 4
            </span>   
        </font>    
</h1>
<h3 style="text-align:CENTER">   
      <font color = white >
            <span style='font-family:Georgia'>
                By : Team 9
            </span>   
        </font>    
</h3>
<hr style="width:100%;height:5px;border-width:0;color:gray;background-color:gray">
<center>

## Import Python Libraries:

In [1]:
# Lets import the required libraries and packages
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.metrics import precision_recall_curve, roc_auc_score
from sklearn.metrics import precision_score, recall_score, confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, f1_score
import warnings
warnings.filterwarnings("ignore")

In [2]:
# load data
fraud_test = pd.read_csv("fraudTest.csv")
fraud_test

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
555715,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
555716,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
555717,555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
555718,555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [3]:
# Lets check the info to see the types of the feature variables and the null values present
fraud_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  object
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  object
 4   category               555719 non-null  object
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object
 7   last                   555719 non-null  object
 8   gender                 555719 non-null  object
 9   street                 555719 non-null  object
 10  city                   555719 non-null  object
 11  state                  555719 non-null  object
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  object
 17  dob                    555719 non-null  object
 18  trans_num              555719 non-null  object
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 97.5+ MB

In [4]:
# Summary of the dataset
fraud_test.describe(include='all')

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
count,555719.000000,555719,5.557190e+05,555719,555719,555719.000000,555719,555719,555719,555719,...,555719.000000,555719.000000,5.557190e+05,555719,555719,555719,5.557190e+05,555719.000000,555719.000000,555719.000000
unique,NaN,544760,NaN,693,14,NaN,341,471,2,924,...,NaN,NaN,NaN,478,910,555719,NaN,NaN,NaN,NaN
top,NaN,2020-12-19 16:02:22,NaN,fraud_Kilback LLC,gas_transport,NaN,Christopher,Smith,F,444 Robert Mews,...,NaN,NaN,NaN,Film/video editor,1977-03-23,2da90c7d74bd46a0caf3777415b3ebd3,NaN,NaN,NaN,NaN
freq,NaN,4,NaN,1859,56370,NaN,11443,12146,304886,1474,...,NaN,NaN,NaN,4119,2408,1,NaN,NaN,NaN,NaN
mean,277859.000000,NaN,4.178387e+17,NaN,NaN,69.392810,NaN,NaN,NaN,NaN,...,38.543253,-90.231325,8.822189e+04,NaN,NaN,NaN,1.380679e+09,38.542798,-90.231380,0.003860
std,160422.401459,NaN,1.309837e+18,NaN,NaN,156.745941,NaN,NaN,NaN,NaN,...,5.061336,13.721780,3.003909e+05,NaN,NaN,NaN,5.201104e+06,5.095829,13.733071,0.062008
min,0.000000,NaN,6.041621e+10,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,20.027100,-165.672300,2.300000e+01,NaN,NaN,NaN,1.371817e+09,19.027422,-166.671575,0.000000
25%,138929.500000,NaN,1.800429e+14,NaN,NaN,9.630000,NaN,NaN,NaN,NaN,...,34.668900,-96.798000,7.410000e+02,NaN,NaN,NaN,1.376029e+09,34.755302,-96.905129,0.000000
50%,277859.000000,NaN,3.521417e+15,NaN,NaN,47.290000,NaN,NaN,NaN,NaN,...,39.371600,-87.476900,2.408000e+03,NaN,NaN,NaN,1.380762e+09,39.376593,-87.445204,0.000000
75%,416788.500000,NaN,4.635331e+15,NaN,NaN,83.010000,NaN,NaN,NaN,NaN,...,41.894800,-80.175200,1.968500e+04,NaN,NaN,NaN,1.385867e+09,41.954163,-80.264637,0.000000
max,555718.000000,NaN,4.992346e+18,NaN,NaN,22768.110000,NaN,NaN,NaN,NaN,...,65.689900,-67.950300,2.906700e+06,NaN,NaN,NaN,1.388534e+09,66.679297,-66.952026,1.000000

### Duplicate value analysis

In [5]:
# Dimension of data set
print(fraud_test.shape)
fraud_test.drop_duplicates()
print(fraud_test.shape)

(555719, 23)
(555719, 23)

## Data Cleaning Proceess

In [6]:
# Lets check the null values present in the dataset in each column
print(fraud_test.isnull().sum())

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

No null values found

### Dropping Columns

In [7]:
# Lets delete unwanted column
fraud_test= fraud_test.drop(['Unnamed: 0'],axis=1)
fraud_test= fraud_test.drop(['first'],axis=1)
fraud_test= fraud_test.drop(['last'],axis=1)

fraud_test.shape

(555719, 20)

In [8]:
# Identifying columns which has only one unique value
print(fraud_test.nunique(dropna=False).sort_values())

is_fraud                      2
gender                        2
category                     14
state                        50
job                         478
merchant                    693
city_pop                    835
city                        849
dob                         910
long                        910
lat                         910
zip                         912
street                      924
cc_num                      924
amt                       37256
unix_time                544760
trans_date_trans_time    544760
merch_lat                546490
merch_long               551770
trans_num                555719
dtype: int64

### Data Transformation

In [9]:
# Lets convert the columns to appropriate formats
fraud_test['trans_date_trans_time']= pd.to_datetime(fraud_test['trans_date_trans_time'])

In [10]:
fraud_test['dob'] = pd.to_datetime(fraud_test['dob'], errors='coerce')

In [11]:
fraud_test['trans_Date']=fraud_test.trans_date_trans_time.dt.date
fraud_test['trans_Time']=fraud_test.trans_date_trans_time.dt.time
fraud_test.trans_Date = pd.to_datetime(fraud_test['trans_Date'],format='%Y-%m-%d')

In [12]:
fraud_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  555719 non-null  datetime64[ns]
 1   cc_num                 555719 non-null  int64
 2   merchant               555719 non-null  object
 3   category               555719 non-null  object
 4   amt                    555719 non-null  float64
 5   gender                 555719 non-null  object
 6   street                 555719 non-null  object
 7   city                   555719 non-null  object
 8   state                  555719 non-null  object
 9   zip                    555719 non-null  int64
 10  lat                    555719 non-null  float64
 11  long                   555719 non-null  float64
 12  city_pop               555719 non-null  int64
 13  job                    555719 non-null  object
 14  dob                    555719 non-null  datetime64[ns]
 15  trans_num              555719 non-null  object
 16  unix_time              555719 non-null  int64
 17  merch_lat              555719 non-null  float64
 18  merch_long             555719 non-null  float64
 19  is_fraud               555719 non-null  int64
 20  trans_Date             555719 non-null  datetime64[ns]
 21  trans_Time             555719 non-null  object
dtypes: datetime64[ns](3), float64(5), int64(5), object(9)
memory usage: 93.3+ MB

### Binning of `state` column as it is having 51 unique values

In [13]:
def label_states (row):
    if row['state'] in ['CT','ME','MA','NH','NJ','NY','PA','RI','VT']:
        return 'Northeast'
    if row['state'] in ['IL','IN','IA','KS','MI','MN','MO','NE','ND','OH','SD','WI']:
        return 'Midwest'
    if row['state'] in ['AL','AR','DE','DC','FL','GA','KY','LA','MD','MS','NC','OK','SC','TN','Tx','VA','WV']:
        return 'South'
    else:
        return 'West'

In [14]:
fraud_test['state_bin'] = fraud_test.apply(lambda row: label_states(row), axis=1)
fraud_test

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,city,state,zip,...,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,trans_Date,trans_Time,state_bin
0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,M,351 Darlene Green,Columbia,SC,29209,...,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,2020-06-21,12:14:25,South
1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,F,3638 Marsh Union,Altonah,UT,84002,...,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,2020-06-21,12:14:33,West
2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,F,9333 Valentine Point,Bellmore,NY,11710,...,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0,2020-06-21,12:14:53,Northeast
3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,M,32941 Krystal Mill Apt. 552,Titusville,FL,32780,...,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0,2020-06-21,12:15:15,South
4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,M,5783 Evan Roads Apt. 465,Falmouth,MI,49632,...,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0,2020-06-21,12:15:17,Midwest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,M,558 Michael Estates,Luray,MO,63453,...,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0,2020-12-31,23:59:07,Midwest
555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,M,572 Davis Mountains,Lake Jackson,TX,77566,...,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0,2020-12-31,23:59:09,West
555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,F,144 Evans Islands Apt. 683,Burbank,WA,99323,...,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0,2020-12-31,23:59:15,West
555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,M,7020 Doyle Stream Apt. 951,Mesa,ID,83643,...,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0,2020-12-31,23:59:24,West
555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,M,830 Myers Plaza Apt. 384,Edmond,OK,73034,...,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0,2020-12-31,23:59:34,South

In [15]:
fraud_test["state_bin"].describe()

count     555719
unique         4
top        South
freq      170884
Name: state_bin, dtype: object

### Deriving `age` on transaction day from "dob" variable and binning of age variable

In [16]:

fraud_test["age"] = fraud_test["dob"].apply(lambda x: (pd.to_datetime('now').year - x.year))

### Binning of age

In [17]:
bin_manual = [0, 20, 30, 40, 50, 60, 70, 80, 90, 100]
labs = ['0-20', '20-30', '30-40', '40-50','50-60','60-70','70-80', '80-90','90-100']
fraud_test['age_bin'] = pd.cut(fraud_test.age, bins=bin_manual, labels=labs)

###  Deriving `trans_Year`, `trans_year_month`, `trans_Month`, `trans_Hour`, `trans_Day`, `trans_weekday` of transaction from trans_date_trans_time variable

In [18]:
fraud_test['trans_Year']=fraud_test.trans_Date.dt.year
fraud_test['trans_year_month'] = fraud_test.trans_Date.dt.to_period('M')
fraud_test['trans_Month']=fraud_test.trans_Date.dt.month
fraud_test['trans_Hour']=fraud_test.trans_date_trans_time.dt.hour
fraud_test['trans_Day']=fraud_test.trans_Date.dt.day
fraud_test['trans_weekday'] = fraud_test.trans_Date.dt.day_name()

fraud_test.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,city,state,zip,...,trans_Time,state_bin,age,age_bin,trans_Year,trans_year_month,trans_Month,trans_Hour,trans_Day,trans_weekday
0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,M,351 Darlene Green,Columbia,SC,29209,...,12:14:25,South,56,50-60,2020,2020-06,6,12,21,Sunday
1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,F,3638 Marsh Union,Altonah,UT,84002,...,12:14:33,West,34,30-40,2020,2020-06,6,12,21,Sunday
2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,F,9333 Valentine Point,Bellmore,NY,11710,...,12:14:53,Northeast,54,50-60,2020,2020-06,6,12,21,Sunday
3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,M,32941 Krystal Mill Apt. 552,Titusville,FL,32780,...,12:15:15,South,37,30-40,2020,2020-06,6,12,21,Sunday
4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,M,5783 Evan Roads Apt. 465,Falmouth,MI,49632,...,12:15:17,Midwest,69,60-70,2020,2020-06,6,12,21,Sunday

### Checking the correlations between the variables

In [19]:
# lets check the correlation amongst the features
# Select only the numeric columns
numeric_cols = fraud_test.select_dtypes(include=[np.number])

# Compute the correlation matrix
cor = numeric_cols.corr()


# Define a threshold for high correlation
threshold = 0.8

# Find pairs of features with high correlation
high_corr_pairs = []
for i in range(len(cor.columns)):
    for j in range(i):
        if abs(cor.iloc[i, j]) > threshold:
            high_corr_pairs.append((cor.columns[i], cor.columns[j], cor.iloc[i, j]))

# Display the high correlation pairs
for pair in high_corr_pairs:
    print(f"Columns '{pair[0]}' and '{pair[1]}' have a correlation of {pair[2]:.2f}")

Columns 'long' and 'zip' have a correlation of -0.91
Columns 'merch_lat' and 'lat' have a correlation of 0.99
Columns 'merch_long' and 'zip' have a correlation of -0.91
Columns 'merch_long' and 'long' have a correlation of 1.00
Columns 'trans_Month' and 'unix_time' have a correlation of 0.99

### Dropping the variables who have high correlation values

In [20]:
# Columns to drop based on the correlation analysis
columns_to_drop = ['merch_lat', 'merch_long']  # Choose to keep 'lat' and 'zip' or based on other criteria

# Drop the columns
fraud_test = fraud_test.drop(columns=columns_to_drop)

# Display the shape of the new DataFrame to verify columns have been dropped
print(fraud_test.shape)

(555719, 29)

In [21]:
# Drop the 'trans_date_time' column from the DataFrame in place
fraud_test.drop(columns=['trans_date_trans_time','state'], axis=1, inplace=True)

# Display the first few rows of the modified DataFrame to verify the column has been removed
print(fraud_test.head())

             cc_num                              merchant        category  \
0  2291163933867244                 fraud_Kirlin and Sons   personal_care
1  3573030041201292                  fraud_Sporer-Keebler   personal_care
2  3598215285024754  fraud_Swaniawski, Nitzsche and Welch  health_fitness
3  3591919803438423                     fraud_Haley Group        misc_pos
4  3526826139003047                 fraud_Johnston-Casper          travel

     amt gender                       street        city    zip      lat  \
0   2.86      M            351 Darlene Green    Columbia  29209  33.9659
1  29.84      F             3638 Marsh Union     Altonah  84002  40.3207
2  41.28      F         9333 Valentine Point    Bellmore  11710  40.6729
3  60.05      M  32941 Krystal Mill Apt. 552  Titusville  32780  28.5697
4   3.19      M     5783 Evan Roads Apt. 465    Falmouth  49632  44.2529

       long  ...  trans_Time  state_bin age age_bin  trans_Year  \
0  -80.9355  ...    12:14:25      South  56   50-60        2020
1 -110.4360  ...    12:14:33       West  34   30-40        2020
2  -73.5365  ...    12:14:53  Northeast  54   50-60        2020
3  -80.8191  ...    12:15:15      South  37   30-40        2020
4  -85.0170  ...    12:15:17    Midwest  69   60-70        2020

   trans_year_month trans_Month trans_Hour trans_Day  trans_weekday
0           2020-06           6         12        21         Sunday
1           2020-06           6         12        21         Sunday
2           2020-06           6         12        21         Sunday
3           2020-06           6         12        21         Sunday
4           2020-06           6         12        21         Sunday

[5 rows x 27 columns]

In [22]:

# `` Binning 'trans_Hour' into categories
def categorize_hour(hour):
    if 0 <= hour < 6:
        return 'Night'
    elif 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 18:
        return 'Afternoon'
    else:
        return 'Evening'

fraud_test['hour_bin'] = fraud_test['trans_Hour'].apply(categorize_hour)

# One-Hot Encoding 'hour_bin'
fraud_test = pd.get_dummies(fraud_test, columns=['hour_bin'], prefix='hour_bin')


# One-Hot Encoding for nominal features like 'category' or 'state'
fraud_test = pd.get_dummies(fraud_test, columns=['category', 'state_bin'], prefix=['category', 'state'])

In [23]:
import joblib


# Load the saved models, scalers, and encoders
scaler = joblib.load('scaler.joblib')
label_encoder_age_bin = joblib.load('label_encoder.joblib')
best_model = joblib.load('logisticModelRFE.joblib')
rfe = joblib.load('rfe_selector.joblib')

In [24]:
# Label Encoding (if needed) for ordinal features 
from sklearn.preprocessing import LabelEncoder

fraud_test['age_bin_encoded'] = label_encoder_age_bin.transform(fraud_test['age_bin'])

In [25]:
# One-Hot Encoding the 'gender' column
fraud_test = pd.get_dummies(fraud_test, columns=['gender'], prefix='gender')

# Display the first few rows to verify the encoding
fraud_test.head()

,cc_num,merchant,amt,street,city,zip,lat,long,city_pop,job,...,category_shopping_net,category_shopping_pos,category_travel,state_Midwest,state_Northeast,state_South,state_West,age_bin_encoded,gender_F,gender_M
0,2291163933867244,fraud_Kirlin and Sons,2.86,351 Darlene Green,Columbia,29209,33.9659,-80.9355,333497,Mechanical engineer,...,False,False,False,False,False,True,False,4,False,True
1,3573030041201292,fraud_Sporer-Keebler,29.84,3638 Marsh Union,Altonah,84002,40.3207,-110.4360,302,"Sales professional, IT",...,False,False,False,False,False,False,True,2,True,False
2,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",41.28,9333 Valentine Point,Bellmore,11710,40.6729,-73.5365,34496,"Librarian, public",...,False,False,False,False,True,False,False,4,True,False
3,3591919803438423,fraud_Haley Group,60.05,32941 Krystal Mill Apt. 552,Titusville,32780,28.5697,-80.8191,54767,Set designer,...,False,False,False,False,False,True,False,2,False,True
4,3526826139003047,fraud_Johnston-Casper,3.19,5783 Evan Roads Apt. 465,Falmouth,49632,44.2529,-85.0170,1126,Furniture designer,...,False,False,True,True,False,False,False,5,False,True

In [26]:
fraud_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 49 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   cc_num                   555719 non-null  int64
 1   merchant                 555719 non-null  object
 2   amt                      555719 non-null  float64
 3   street                   555719 non-null  object
 4   city                     555719 non-null  object
 5   zip                      555719 non-null  int64
 6   lat                      555719 non-null  float64
 7   long                     555719 non-null  float64
 8   city_pop                 555719 non-null  int64
 9   job                      555719 non-null  object
 10  dob                      555719 non-null  datetime64[ns]
 11  trans_num                555719 non-null  object
 12  unix_time                555719 non-null  int64
 13  is_fraud                 555719 non-null  int64
 14  trans_Date               555719 non-null  datetime64[ns]
 15  trans_Time               555719 non-null  object
 16  age                      555719 non-null  int64
 17  age_bin                  555719 non-null  category
 18  trans_Year               555719 non-null  int32
 19  trans_year_month         555719 non-null  period[M]
 20  trans_Month              555719 non-null  int32
 21  trans_Hour               555719 non-null  int32
 22  trans_Day                555719 non-null  int32
 23  trans_weekday            555719 non-null  object
 24  hour_bin_Afternoon       555719 non-null  bool
 25  hour_bin_Evening         555719 non-null  bool
 26  hour_bin_Morning         555719 non-null  bool
 27  hour_bin_Night           555719 non-null  bool
 28  category_entertainment   555719 non-null  bool
 29  category_food_dining     555719 non-null  bool
 30  category_gas_transport   555719 non-null  bool
 31  category_grocery_net     555719 non-null  bool
 32  category_grocery_pos     555719 non-null  bool
 33  category_health_fitness  555719 non-null  bool
 34  category_home            555719 non-null  bool
 35  category_kids_pets       555719 non-null  bool
 36  category_misc_net        555719 non-null  bool
 37  category_misc_pos        555719 non-null  bool
 38  category_personal_care   555719 non-null  bool
 39  category_shopping_net    555719 non-null  bool
 40  category_shopping_pos    555719 non-null  bool
 41  category_travel          555719 non-null  bool
 42  state_Midwest            555719 non-null  bool
 43  state_Northeast          555719 non-null  bool
 44  state_South              555719 non-null  bool
 45  state_West               555719 non-null  bool
 46  age_bin_encoded          555719 non-null  int64
 47  gender_F                 555719 non-null  bool
 48  gender_M                 555719 non-null  bool
dtypes: bool(24), category(1), datetime64[ns](2), float64(3), int32(4), int64(7), object(7), period[M](1)
memory usage: 106.5+ MB

In [27]:
# One-hot encode categorical columns
categorical_cols = ['trans_weekday']  # Add other categorical columns as needed
fraud_test = pd.get_dummies(fraud_test, columns=categorical_cols)

In [28]:
fraud_test.drop(columns=['gender_F'],axis=1, inplace=True) 
fraud_test.drop(columns=['trans_num'],axis=1, inplace=True)

In [29]:
# Frequency Encoding for high-cardinality categorical columns
def frequency_encoding(df, column):
    freq_encoding = df[column].value_counts()
    df[column + '_freq'] = df[column].map(freq_encoding)
    return df

# Apply frequency encoding to 'merchant', 'street', 'city', 'job'
columns_to_encode = ['merchant', 'street', 'city', 'job']
for col in columns_to_encode:
    fraud_test = frequency_encoding(fraud_test, col)
    fraud_test.drop(columns=[col], inplace=True)  # Drop original column if no longer needed

fraud_test.head()

,cc_num,amt,zip,lat,long,city_pop,dob,unix_time,is_fraud,trans_Date,...,trans_weekday_Monday,trans_weekday_Saturday,trans_weekday_Sunday,trans_weekday_Thursday,trans_weekday_Tuesday,trans_weekday_Wednesday,merchant_freq,street_freq,city_freq,job_freq
0,2291163933867244,2.86,29209,33.9659,-80.9355,333497,1968-03-19,1371816865,0,2020-06-21,...,False,False,True,False,False,False,736,640,640,2430
1,3573030041201292,29.84,84002,40.3207,-110.4360,302,1990-01-17,1371816873,0,2020-06-21,...,False,False,True,False,False,False,785,837,837,2535
2,3598215285024754,41.28,11710,40.6729,-73.5365,34496,1970-10-21,1371816893,0,2020-06-21,...,False,False,True,False,False,False,755,1073,1073,2587
3,3591919803438423,60.05,32780,28.5697,-80.8191,54767,1987-07-25,1371816915,0,2020-06-21,...,False,False,True,False,False,False,711,663,663,663
4,3526826139003047,3.19,49632,44.2529,-85.0170,1126,1955-07-06,1371816917,0,2020-06-21,...,False,False,True,False,False,False,370,891,891,891

In [30]:
fraud_test.drop(columns=['dob'], inplace=True)

In [31]:
# Drop the original 'trans_Date' column
fraud_test.drop(columns=['trans_Date'], inplace=True)

In [32]:
# Convert 'trans_year_month' (which is a Period) to a numeric format (e.g., YYYYMM)
fraud_test['trans_year_month'] = fraud_test['trans_year_month'].astype(str).str.replace('-', '').astype(int)

In [33]:
# Convert 'trans_Time' to seconds since midnight
fraud_test['trans_Time'] = pd.to_datetime(fraud_test['trans_Time'], format='%H:%M:%S').dt.hour * 3600 + \
                            pd.to_datetime(fraud_test['trans_Time'], format='%H:%M:%S').dt.minute * 60 + \
                            pd.to_datetime(fraud_test['trans_Time'], format='%H:%M:%S').dt.second

In [35]:
# Define features and target variable
X = fraud_test.drop(columns=['is_fraud', 'cc_num','unix_time','age_bin','category_entertainment'])  # Drop irrelevant columns if necessary
y = fraud_test['is_fraud']

In [37]:
# Define features and target variable
X = fraud_test.drop(columns=['cc_num','category_entertainment','age_bin_encoded'])  # Drop irrelevant columns if necessary

In [40]:
X=fraud_test.drop(columns=["cc_num"])

In [41]:
X.columns

Index(['amt', 'zip', 'lat', 'long', 'city_pop', 'trans_Time', 'age',
       'trans_Year', 'trans_year_month', 'trans_Month', 'trans_Hour',
       'trans_Day', 'hour_bin_Afternoon', 'hour_bin_Evening',
       'hour_bin_Morning', 'hour_bin_Night', 'category_food_dining',
       'category_gas_transport', 'category_grocery_net',
       'category_grocery_pos', 'category_health_fitness', 'category_home',
       'category_kids_pets', 'category_misc_net', 'category_misc_pos',
       'category_personal_care', 'category_shopping_net',
       'category_shopping_pos', 'category_travel', 'state_Midwest',
       'state_Northeast', 'state_South', 'state_West', 'age_bin_encoded',
       'gender_M', 'trans_weekday_Friday', 'trans_weekday_Monday',
       'trans_weekday_Saturday', 'trans_weekday_Sunday',
       'trans_weekday_Thursday', 'trans_weekday_Tuesday',
       'trans_weekday_Wednesday', 'merchant_freq', 'street_freq', 'city_freq',
       'job_freq'],
      dtype='object')

In [39]:
X

,amt,zip,lat,long,city_pop,trans_Time,age,trans_Year,trans_year_month,trans_Month,...,trans_weekday_Monday,trans_weekday_Saturday,trans_weekday_Sunday,trans_weekday_Thursday,trans_weekday_Tuesday,trans_weekday_Wednesday,merchant_freq,street_freq,city_freq,job_freq
0,2.86,29209,33.9659,-80.9355,333497,44065,56,2020,202006,6,...,False,False,True,False,False,False,736,640,640,2430
1,29.84,84002,40.3207,-110.4360,302,44073,34,2020,202006,6,...,False,False,True,False,False,False,785,837,837,2535
2,41.28,11710,40.6729,-73.5365,34496,44093,54,2020,202006,6,...,False,False,True,False,False,False,755,1073,1073,2587
3,60.05,32780,28.5697,-80.8191,54767,44115,37,2020,202006,6,...,False,False,True,False,False,False,711,663,663,663
4,3.19,49632,44.2529,-85.0170,1126,44117,69,2020,202006,6,...,False,False,True,False,False,False,370,891,891,891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,43.77,63453,40.4931,-91.8912,519,86347,58,2020,202012,12,...,False,False,False,True,False,False,757,628,628,1699
555715,111.84,77566,29.0393,-95.4401,28739,86349,25,2020,202012,12,...,False,False,False,True,False,False,1006,1105,1105,1724
555716,86.88,99323,46.1966,-118.9017,3684,86355,43,2020,202012,12,...,False,False,False,True,False,False,1043,1079,1672,2594
555717,7.99,83643,44.6255,-116.4493,129,86364,59,2020,202012,12,...,False,False,False,True,False,False,346,883,883,883
555718,38.13,73034,35.6665,-97.4798,116001,86374,31,2020,202012,12,...,False,False,False,True,False,False,783,1090,1090,1090

In [42]:
desired_features = [
    'amt', 'trans_Time', 'age', 'trans_year_month', 'trans_Month',
    'trans_Day', 'hour_bin_Afternoon', 'hour_bin_Evening',
    'hour_bin_Morning', 'hour_bin_Night', 'category_grocery_pos',
    'category_health_fitness', 'category_home', 'category_kids_pets',
    'category_misc_net', 'category_shopping_net', 'merchant_freq',
    'street_freq', 'city_freq', 'job_freq'
]
X_test = X[desired_features]

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

X_test_scaled = scaler.fit_transform(X_test)

In [44]:
# Make predictions
y_pred_unseen = best_model.predict(X_test_scaled)

In [45]:

# Print the classification report for the best model
print("Classification Report for the Best Model:")
print(classification_report(y, y_pred_unseen))

Classification Report for the Best Model:
              precision    recall  f1-score   support

           0       1.00      0.88      0.94    553574
           1       0.02      0.79      0.05      2145

    accuracy                           0.88    555719
   macro avg       0.51      0.84      0.49    555719
weighted avg       1.00      0.88      0.93    555719